[package]
name = "sampler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
midir = "0.9.0"
quad-snd = { git = "https://github.com/kirinokirino/quad-snd" }
